#!/bin/bash
set -euo pipefail

VERSION_FILE="$CI_PRIMARY_REPOSITORY_PATH/VERSION"
BASE_VERSION=$(cat "$VERSION_FILE")

if [ "${CI_BRANCH:-}" = "main" ]; then
    MARKETING_VERSION="$BASE_VERSION"
else
    MARKETING_VERSION="${BASE_VERSION}.${CI_BUILD_NUMBER:-1}"
fi

PBXPROJ="$CI_PRIMARY_REPOSITORY_PATH/Tensio.xcodeproj/project.pbxproj"
sed -i '' "s/MARKETING_VERSION = .*;/MARKETING_VERSION = $MARKETING_VERSION;/g" "$PBXPROJ"
sed -i '' "s/CURRENT_PROJECT_VERSION = .*;/CURRENT_PROJECT_VERSION = ${CI_BUILD_NUMBER:-1};/g" "$PBXPROJ"
